---
- name: Remove o usu치rio Aluno e deleta seus arquivos
  hosts: groupo_de_hosts
  become: yes  # This is necessary to execute commands with root privileges
  
  tasks:
    - name: Remove u usu치rio
      user:
        name: Aluno
        state: absent  # So remove se est치 presente
      
    - name: Deleta a home do usu치rio
      file:
        path: /home/Aluno
        state: absent
        recurse: yes
